services:

  envoy:
    image: envoyproxy/envoy:v1.26.0
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--config-path /etc/envoy/envoy.yaml"
    ports:
    - 10000:10000
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  service1-1:
    image: ghcr.io/aak74/btest:latest


  service1-2:
    image: ghcr.io/aak74/btest:latest

